# Generated by Django 6.0.2 on 2026-02-25 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='featured_works/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_provided', models.CharField(choices=[('printing', 'Printing'), ('website', 'Website'), ('branding', 'Branding'), ('videographics', 'Video graphics'), ('uiux', 'Ui ux')], max_length=100)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('primary_image', models.ImageField(upload_to='reviews/primary/')),
                ('secondary_image', models.ImageField(blank=True, null=True, upload_to='reviews/secondary/')),
            ],
        ),
    ]
